input_folder: "folder_input"
output_folder: "folder_output"

transaction_detail_codes:
  dr_cr:
    "175": "CR"
    "195": "CR"
    "238": "CR"
    "252": "CR"
    "357": "CR"
    "399": "CR"
    "475": "DR"
    "495": "DR"
    "501": "DR"
    "512": "DR"
    "555": "DR"
    "564": "DR"
    "595": "DR"
    "631": "DR"
    "654": "DR"
    "699": "DR"
    "905": "CR"
    "906": "CR"
    "910": "CR"
    "911": "CR"
    "915": "CR"
    "920": "CR"
    "925": "CR"
    "930": "CR"
    "935": "CR"
    "936": "CR"
    "938": "CR"
    "950": "DR"
    "951": "DR"
    "952": "DR"
    "953": "DR"
    "955": "DR"
    "956": "DR"
    "960": "DR"
    "961": "DR"
    "962": "DR"
    "970": "DR"
    "971": "DR"
    "975": "DR"
    "980": "DR"
    "985": "DR"
    "986": "DR"
    "987": "DR"
    "988": "DR"

  transaction_description:
    "175": "Cheques"
    "195": "Transfer credits"
    "238": "Dividend"
    "252": "Reversal Entry"
    "357": "Credit adjustment"
    "399": "Miscellaneous credits"
    "475": "Cheques (paid)"
    "495": "Transfer debits"
    "501": "Automatic drawings"
    "512": "Documentary L/C Drawings/Fees"
    "555": "Dishonoured cheques"
    "564": "Loan fees"
    "595": "FlexiPay"
    "631": "Debit adjustment"
    "654": "Debit Interest"
    "699": "Miscellaneous debits"
    "905": "Credit Interest"
    "906": "National nominees credits"
    "910": "Cash"
    "911": "Cash/cheques"
    "915": "Agent Credits"
    "920": "Inter-bank credits"
    "925": "Bankcard credits"
    "930": "Credit balance transfer"
    "935": "Credits summarised"
    "936": "EFTPOS"
    "938": "NFCA credit transactions"
    "950": "Loan establishment fees"
    "951": "Account keeping fees"
    "952": "Unused limit fees"
    "953": "Security fees"
    "955": "Charges"
    "956": "National nominee debits"
    "960": "Stamp duty-cheque book"
    "961": "Stamp duty"
    "962": "Stamp duty-security"
    "970": "State government tax"
    "971": "Federal government tax"
    "975": "Bankcards"
    "980": "Debit balance transfers"
    "985": "Debits summarised"
    "986": "Cheques summarised"
    "987": "Non-cheques summarised"
    "988": "NFCA debit transaction"

  statement_particulars:
    "175": "Cash/Cheques"
    "195": "Transfer"
    "238": "Dividend"
    "252": "Reversal"
    "357": "Adjustment"
    "399": "Miscellaneous credit"
    "475": "All serial numbers"
    "495": "Transfer"
    "501": "Company's name (abbreviated)"
    "512": "Documentary L/C"
    "555": "Dishonoured cheques"
    "564": "Loan fee"
    "595": "Merchant name"
    "631": "Adjustment"
    "654": "Interest"
    "699": "Miscellaneous debit"
    "905": "Interest"
    "906": "National nominees"
    "910": "Cash"
    "911": "Cash/cheques"
    "915": "Agent number advised"
    "920": "Company's name (abbreviated)"
    "925": "Bankcard"
    "930": "Balance transfer"
    "935": "Not applicable"
    "936": "Merchant name"
    "938": "Not applicable"
    "950": "Establishment fee"
    "951": "Account keeping fee"
    "952": "Unused limit fee"
    "953": "Security fee"
    "955": "Charge (or description)"
    "956": "National nominees"
    "960": "Cheque book"
    "961": "Stamp duty"
    "962": "Security stamp duty"
    "970": "State government credit tax"
    "971": "Federal government debit tax"
    "975": "Bankcard"
    "980": "Balance transfers"
    "985": "Not applicable"
    "986": "Not applicable"
    "987": "Not applicable"
    "988": "Not applicable"
